# Generated by Django 4.0.4 on 2023-01-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Default name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Default name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.user'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccination_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationcenter'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.center'),
        ),
    ]
